### ISSUE TITLE
Does it work without groundpi？

### ISSUE THREAD

**Issue by cgrrty** [OpenHD/QOpenHD#125]
Hi
  Just use a computer with wifi (QOpenHD installed) and an airpi,not use groundpi， Whether it can work normally, so the cost is lower.
 I don’t know, did I make it clear.

**Comment by kasatka60** [comment]
Wi-Fi on the AR9271/RTL8812AU/mt7601u chip?

**Comment by cgrrty** [comment]
我是想说，地面端只使用一台带wifi网卡的笔记本电脑，地面端不使用树莓。飞机端使用树莓派。是否可行？

**Comment by pilotnbr1** [comment]
Not supported yet but coming soon

**Comment by cgrrty** [comment]
Hi
  Regarding this, where can I see the development progress? @pilotnbr1

**Comment by pilotnbr1** [comment]
> Hi
> Regarding this, where can I see the development progress? @pilotnbr1

https://discuss.openhdfpv.com/t/informal-openhd-project-roadmap/38

If you are happy with the answers would you please close the issue.
