### ISSUE TITLE
wrong longitude home point

### ISSUE THREAD

**Issue by kasatka60** [OpenHD/QOpenHD#127]
Inav 2.5.1
Mavlink
wrong longitude home point
Openhd 2.0.0rc7
Qopenhd 0.4.0b5
![758FB7B6-BB6A-4B89-A1A4-F9F27E3E6310](https://user-images.githubusercontent.com/61105679/85211421-b6ded080-b351-11ea-9241-5a878e59d4e1.jpeg)

**Comment by pilotnbr1** [comment]
Looks like openhd.lat is in the widgetdetail field for openhd.lon

**Comment by steveatinfincia** [comment]
Fixed :)
