### ISSUE TITLE
Add sky view of GPS satellites

### ISSUE THREAD

**Issue by steveatinfincia** [OpenHD/QOpenHD#13]
It would be cool to have a view of where the satellites are in the sky overhead, and might prove useful in some cases. You would be able to see if they're not spread out as much as they should be (affects horizontal accuracy, apparently), and you could see if something is blocking line of sight or not in a particular direction.

**Comment by pilotnbr1** [comment]
Sounds interesting. The geometry of the satellite constellation can be an interesting consideration, particularily when you have terrain or building blocking the view. 

Sometimes when the sats are all bunched in one area of the sky you may be receiving quite a few signals but your receiver has harder time triangulating position in that scenario. It is call a horizontal dillution of precision (in the hobby just called hdop)
