### ISSUE TITLE
[Feature Request] Option for fullscreen or black bars on mobile

### ISSUE THREAD

**Issue by TheNewJavaman** [OpenHD/QOpenHD#142]
My phone (Samsung S9) only shows the video fullscreen/zoomed in, effectively deleting vertical FOV. Is there an option to not do that? If not, feature request :)

**Comment by steveatinfincia** [comment]
Hey :D

This is odd, nothing in QOpenHD crops video. What was the openhd resolution and sensor mode set to?

**Comment by TheNewJavaman** [comment]
> Hey :D
> 
> This is odd, nothing in QOpenHD crops video. What was the openhd resolution and sensor mode set to?

I'm not sure when this happened, but it doesn't anymore. Guess it's fixed.
