### ISSUE TITLE
Feature request: Use a different port than 14550 for Mavlink telemetry

### ISSUE THREAD

**Issue by fingadar** [OpenHD/QOpenHD#151]
In OpenHD's hotspot mode: 
If QOpenHD would use a different port than 14550 (parallel to 14550) for it's Mavlink telemetry (when just listening to the telemetry, for the OSD), you could open Mission Planner or any other GCS (like UgCS, in my case), parallel to the nice QOpenHD. 

The changes for that should be very small (on OpenHD side and QOpenHD side).

That would be perfect!

**Comment by raphaelscholle** [comment]
issue will be resolved in later versions
