### ISSUE TITLE
ADSB Inefficiency

### ISSUE THREAD

**Issue by pilotnbr1** [OpenHD/QOpenHD#163]
When reading the network response from Opensky we read it into a string. It sounds like reading it into a bytearray would be much more efficient.

Otherwise opensky and adsb in themselves do not seem to add much cpu overhead...

**Comment by steveatinfincia** [comment]
QString uses a QByteArray internally, I would bet if there’s overhead it’s from json decoding and any looping.

**Comment by pilotnbr1** [comment]
Gotcha! I’ll close this and not worry about it unless we see some real evidence of higher cpu use
