### ISSUE TITLE
Cant read settings from GND in android app under OxygenOS OnePlus 7

### ISSUE THREAD

**Issue by bjoern79de** [OpenHD/QOpenHD#166]
The stream and OSD is running, but the settings are not readable.

**Comment by bjoern79de** [comment]
Already found the issue: The ABI arm64-v8a was missing.
I guess it should be included into the Release apk to support such devices.

**Comment by steveatinfincia** [comment]
I used to build arm64 releases but people complained about it being confusing.

I’ll start doing it again.
