### ISSUE TITLE
FR qopenhd waypoints

### ISSUE THREAD

**Issue by schs2** [OpenHD/QOpenHD#169]
I fly on arducopter/arduplate with auto missions.
Can be add widget to show info:
1) next waipoint number
2) distance to next waypoint
3) next waypoint type.

**Comment by steveatinfincia** [comment]
Yes, this just requires listening to a few Mavlink messages and showing the values on the screen.

**Comment by schs2** [comment]
Thanks!

**Comment by pilotnbr1** [comment]
The number of total missions items and current mission item are easily displayed and done here-
https://github.com/pilotnbr1/QOpenHD

Distance would be easy to do but having issues with the missionwaypoint model in qt. Need another set of eyes on this now.
