### ISSUE TITLE
2.1 - Create an update button for qopenhd

### ISSUE THREAD

**Issue by MacDaddyFPV** [OpenHD/QOpenHD#270]
For 2.1 We would like to have some buttons in the about screen of Qopenhd to update Qopenhd itself.
There should be one button the checks for any updates and if an update is found it then enables an update button. The update button should then update Qopenhd.

**Comment by Consti10** [comment]
probably won't fix, since QOpenHD is published with each OpenHD image release on embedded platforms and (TODO) on android and ios we'l need to use the android / ios play store and publish updates there
