### ISSUE TITLE
Enhancement: Please Build Oculus quest2 view-compatible apk

### ISSUE THREAD

**Issue by njozsef** [OpenHD/QOpenHD#299]
Hi developers!

It would be great to build an Oculus-quest2 compatible apk. Actually qopenhd still works, but only in 2d mode.
The current apk can be installed with Sidequest (adb w. Gui) only since quest firmware> = v38.
Thank you! Jozsef

![com oculus shellenv-20220326-175953](https://user-images.githubusercontent.com/3214519/160252392-3a02fd8d-eb53-4e9b-ab0c-63ddfc6f6b1f.jpg)

**Comment by Consti10** [comment]
Usable latency would require a native oculus build
