### ISSUE TITLE
Migrate qopenhd from qt 5 to 6

### ISSUE THREAD

**Issue by pilotnbr1** [OpenHD/QOpenHD#305]
Qt 5.15 is getting old and now looking into migrating qopenhd to Qt 6.X

PROS:
- dependecy future proofing
- get qt shader tools. But no present plans to use them

CONS:
- more work... some of it will be platform specific. Nobody currently debugs all platforms like Stephen
- mapbox-gl is not a supported plugin. MaplibreGL looks to be the new solution

Current errors seen while upgrading:
1) Mapbox plugin related
2) OSM plugin for maps error probably related to Mapbox
3) QT x11extras (https://doc.qt.io/qt-6/extras-changes-qt6.html) solution will be somewhat platform dependant
4) QT Location - no plans to port.. Must switch to QT positioning
5) QT gamepads depreciated. probably not a big deal as we use 3rd part qt joystick But need to remove gamepad code
5) QT android extras will probably need some attention for android
6) QT openGL will need attention most likely
7) QT speech supposedly being ported in qt 6.4
8) Qt Windows Extras might need attention for windows

**Comment by pilotnbr1** [comment]
Maplibre is not really targetting qml. The efforts to get it to work on QML have required QT location. Qt Location is also depreciated in QT 6. So the only working Maplibre does a work around using "MSVC" and the performance sounds like its bad https://github.com/ntadej/qt-geoservices-maplibre

Not having mapping is deal breaker for me while weighing 5.15 vs 6.x . As of now does not seem worth the effort to switch.

**Comment by pilotnbr1** [comment]
ArcGIS Runtime API for Qt might be an option for mapping in qt6. We would be getting back into needing an api key/token . Not clear on how that distributes when its deployed in their "essentials" plan

**Comment by pilotnbr1** [comment]
QT 6.2 seems to be getting some map support using maplibre as a plugin. Not sure about linux support.
https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-96795

To try it need QtPositioning and QtShaderTools which are not installed by default

**Comment by pilotnbr1** [comment]
qt 5 works with cmake. So not a problem switching away from qmake

**Comment by raphaelscholle** [comment]
We updated to 5.15.4, so I think with all it's problems we're currently not interested in updating to 6.x

**Comment by hadogenes** [comment]
Will this issue will be reopened, because Qt5 is now unmaintained
https://endoflife.date/qt

**Comment by raphaelscholle** [comment]
we can reopen this and i can say that we're already working on it
