### ISSUE TITLE
Onboard wifi only.. possible?

### ISSUE THREAD

**Issue by CorruptName** [OpenHD/QOpenHD#309]
Hello, is it possible to use a single pi3 or similar to act as the air pi & connect to the openhd android app?
This reason is that I'm making a small camera rover to inspect trucks at work (underneath) and don't need range beyond the built-in wifi.
Edit: this would also make it controllable with only an Android device and no need to carry a ground station.
Thanks in advance!

**Comment by raphaelscholle** [comment]
It isn't doable without some code patches, but technically it should be doable, just not with "normal openhd". 
Currently there is no real demand in that feature and it would break some functionality. So you need to enable this yourself.

You could try using ZeroTier, theoretically if you connect the airpi to wifi it should be able to transmit via that and would act as LTE(https://openhd.gitbook.io/open-hd/advanced-setup/lte-connection). Never tried it, but could work.
