### ISSUE TITLE
Side by side duplicated video playback needed.

### ISSUE THREAD

**Issue by lukolszewski** [OpenHD/QOpenHD#317]

**Comment by lukolszewski** [comment]
Introduction / Motivation
The newly developed VR mode is great. However, not everyone has dual camera setup to take advantage of it.

It would be great if the single video feed could be duplicated side by side. It would allow the android QOpenHD App to be used with GearVR, or Google cardboard for very immersive experience.

What is needed?
Video duplicated side by side with ability to scale the videos and change separation similarly how it is done for the OSD. 

I hope this can be solved?

**Comment by Consti10** [comment]
Vr Mode was removed in evo, it is too nieche.
