### ISSUE TITLE
Warn the user when vehicle is going out of range or losing RC control

### ISSUE THREAD

**Issue by steveatinfincia** [OpenHD/QOpenHD#32]
The simplest UI would be to turn the upper bar yellow (it's currently red when the vehicle is armed), and announce it with the speech system.

As for the way to decide whether the vehicle is about to go out of range or losing RC control, that is a little more involved but could be a combination of RSSI, distance, and perhaps the rate of lost packets.

**Comment by pilotnbr1** [comment]
Would be a great feature but as you say a tough thing to predict. I think vehicle movement makes it tough as antenna position and vehicle shadowing create a high degree of variability in signal reception
