### ISSUE TITLE
invalid conversion from ‘AVCodec**’ to ‘const AVCodec**’

### ISSUE THREAD

**Issue by Zipdox** [OpenHD/QOpenHD#350]
On the 2.2.3-evo-consti-test branch.
```
../app/exp/avcodec_decoder.cpp:487:69: error: invalid conversion from ‘AVCodec**’ to ‘const AVCodec**’ [-fpermissive]
  487 |     ret = av_find_best_stream(input_ctx, AVMEDIA_TYPE_VIDEO, -1, -1,(AVCodec**) &decoder, 0);
      |                                                                     ^~~~~~~~~~~~~~~~~~~~
      |                                                                     |
      |                                                                     AVCodec**
      ```

**Comment by Consti10** [comment]
yeah, some ffmpeg installations require "(const AVCodec**)", and some require (AVCodec**).
There is no better way than to fix this manually according to what ffmpeg you get on you system.

**Comment by Zipdox** [comment]
Is it version related? I'm sure there's a macro you can use to deal with it

**Comment by Consti10** [comment]
I am pretty sure it is, you can also find it on stackoverflow - but no proper solution(s) as of yet

**Comment by Zipdox** [comment]
![image](https://user-images.githubusercontent.com/42157341/201985963-660859b9-184b-4cb6-902e-6bad7e9c1be1.png)
