### ISSUE TITLE
Home Position not set when using INAV Mavlink telemetry

### ISSUE THREAD

**Issue by tipoman9** [OpenHD/QOpenHD#528]
Respectively, Distance to home and Home vector do not work in flight.
qOpenHD needs a MAVLINK message of  type:
  case MAVLINK_MSG_ID_HOME_POSITION:{....}
to set home position. 
I checked INAV implementation of mavlink protocol, there is imported definition for :
static inline uint16_t mavlink_msg_home_position_pack( .... ) 
type of message,  but it is never called. 
Seems INAV only sends mavlink_msg_gps_raw_int_pack messages.
Which means that home vector and distance to home will never work with INAV.
I see two options - change INAV to implement this type of message.
Or think out some clever way for qOpenHD to get home position.
Either accept the last reported coordinates when an "Armed" message is received from INAV, or if this is not reliable, add the possibility for the user to accept current coordinates as home ones by clicking on the Home Distance indicator for example.

**Comment by Consti10** [comment]
As a temporary solution:
https://github.com/OpenHD/QOpenHD/commit/69c04df4941a53ded369e1653a351c36242ed47c

**Comment by Consti10** [comment]
use last reported coordinates when an "Armed" message is received

**Comment by Consti10** [comment]
or rather, uses the first global position message after the fc is armed to set home position

**Comment by Consti10** [comment]
Since it is already merged & built by the CIs, you can probably just apt update / upgrade.
Please report back if it "works".
inav quirks can be enabled under the QOpenHD dev registry

**Comment by tipoman9** [comment]
I confirm it works. Tested it this week several times, works flawlessly.

**Comment by Consti10** [comment]
So there is a bit more news in this regard:
1) I am trying to convince the inav guys to use the same message like ardupilot to pulish home:
https://github.com/iNavFlight/inav/pull/9072

But they are not too happy about it ;)

So I've qurked it in qopenhd ( a bit differnt now).
The only thing you need to know - with this commit:
https://github.com/OpenHD/QOpenHD/commit/a2d3945ebfe69b6e4bd16387c499c115eeca2b63
and inav hacks enabled the home position now works properly, regardless when you start qopenhd.
