### ISSUE TITLE
USB Joystick function unusable without channel trimming

### ISSUE THREAD

**Issue by sinalco92** [OpenHD/QOpenHD#535]
There is no way to set min. and max. values of the Throttle, Yaw, Pitch and Roll channels. Also trimming Yaw, Pitch and Roll is needed to use USB-Joysticks like DJI-FPV Controller 2 or XBox Controller.

Without this functions there is no solution to use this kind of USB-Joysticks to fly with OpenHD. In theoretical the controller works with the Mavlink protokoll in OpenHD evo 2.3 but without this settings it´s not possible to fly. 

Optional a channel invertation was also helpfull, because some of the USB-Joysticks are have inverted channels. But this can maybe inverted in the FlightController like iNav.

**Comment by raphaelscholle** [comment]
Like discussed a lot, we currently don't see a reason to programm a channel-mapping or trimming or exposure setting for our joystick function.
Why?

1. Most controllers which are usable and actually recommended to fly a model are running some kind of Software which allows for those functions.
2. If the controller doesn't have the ability to be programmed it can also be done on the flight controller itself.

So in our opinion there is no need to do this also in OpenHD
