### ISSUE TITLE
Display rotation does not work properly

### ISSUE THREAD

**Issue by sinalco92** [OpenHD/QOpenHD#536]
I use the official Raspberry Pi 3B+ 7" touch display. Because of the housing of the display, it is necessary to rotate the display 180 degrees in the software settings. 

If I rotate the display in OpenHD 2.3 evo, not everything rotates. For example the drop-down menus are 90 degrees shifted.

**Comment by Consti10** [comment]
yeah, that is a known issue, not much we can do about it, for some reason QT doesn't properly rotate those popups.
Video and HUD should be properly rotated though
