### ISSUE TITLE
Settings are being saved even when they haven't been modified

### ISSUE THREAD

**Issue by steveatinfincia** [OpenHD/QOpenHD#55]
For some reason, ground pi settings are being marked as though they've been modified even when they haven't causing the settings system in the app to save them.

This isn't inherently a problem as long as the settings system is working properly, but it's not necessary either.

**Comment by htcohio** [comment]
Hey,

So you're saying that the ground pi is periodically saving settings or, being triggered to save settings even when they haven't been modified?

That would explain why there are instances where Air & ground lose synchronization with settings even without changing anything.

this has not happened in recent test but in the past it has.

**Comment by steveatinfincia** [comment]
I mean when you open the settings panel and change something like hotspot txpower, and then hit save, the app sends a bunch of other settings to the ground station to be saved as well even though the user hasn't changed them.

Because the other settings aren't actually changed it can't cause a problem with anything else (it's just telling the ground station to write the same value into the settings file that's already there).
