### ISSUE TITLE
Pi image - interface does not respond to touchscreen, mouse is working but pointer is invisible

### ISSUE THREAD

**Issue by msergiu80** [OpenHD/QOpenHD#56]
Hi,

First of all thank you for all your work. I installed the Pi 0.3.1 image and it is working great except 3 minor issues, one being the flight mode not working on the QOHD Osd and the other 2, maybe related, the touch events have no effect on the OSD and mouse works but pointer is invisible, so it is a hard guess of actual screen position to enter the menu and operate changes. My touchscreen is working otherwise (other SD with graphical OS) and also using the QOHD image, through SSH, I can see touch events with evtest, so touch drivers are installed and working. I did not change anything else from the default installation but if needed I can attach logs.

**Comment by steveatinfincia** [comment]
Flight mode will be fixed in a few minutes in 0.3.2, the touchscreen issue I'm going to look at today.

As a workaround you can run QOpenHD on Android (or Windows/Mac) and connect to the ground station hotspot to use drag-and-drop remotely.

**Comment by steveatinfincia** [comment]
Ok the touchscreen issue is fixed in [v0.3.3](https://github.com/OpenHD/QOpenHD/releases/tag/v0.3.3) and the nightly Open.HD image from tonight, [nightly-2020-1-15](https://github.com/OpenHD/Open.HD/releases/tag/nightly-2020-1-15).

I've created another issue for the mouse pointer, #58.
