### ISSUE TITLE
Qopenhd android app crash

### ISSUE THREAD

**Issue by knputyi** [OpenHD/QOpenHD#571]
Raphael said, I should open an issue, because the app crashed twice during my latest flight. App is the latest from Playstore, installed with promo code from Consti, running on my Samsung galaxy tab. Tablet connected through USB - Ethernet adapter to ground pi4. Crash happened when maps gadget was in front, trying to zoom in - out.

**Comment by Consti10** [comment]
should be fixed on the upcoming release.
