### ISSUE TITLE
[FR] add resolution 2592x1520

### ISSUE THREAD

**Issue by whoim2** [OpenHD/QOpenHD#582]
1080p working, 1520p not )

**Comment by raphaelscholle** [comment]
What camera and what Hardware (Decode/Encode) are you using ?

**Comment by whoim2** [comment]
> What camera and what Hardware (Decode/Encode) are you using ?

imx335 gk7205v300 noname china ip cam (openipc fw)

**Comment by raphaelscholle** [comment]
and for the ground ?

**Comment by whoim2** [comment]
> and for the ground ?

nvr as router for android tab, qopenhd for android

**Comment by raphaelscholle** [comment]
you can set a custom resolution if you enable advanced button and select dev_show whitelisted commands

after that you can simply change the resolution with a keyboard 

Also remember .. always nothing supports this resolution, so the encoder and decoder will create issues

**Comment by whoim2** [comment]
Tnx, im try
