### ISSUE TITLE
Mavlink mirror problem

### ISSUE THREAD

**Issue by do1234521** [OpenHD/QOpenHD#611]
Is it possible to mirror the mavlink locally to another UDP port for other programs to use in qopenhd? Other control software like missionplaner and qgc can do it.
I searched all the documents and found no description about it. Could anyone help?

**Comment by Consti10** [comment]
mavlink is distributed by openhd core (the main openhd executable on the ground).
It already has the option for another (secondary) GC to connect via tcp.

Feel free to add a forwarding option in qopenhd too, though.
