### ISSUE TITLE
macOS / Mac App Store support

### ISSUE THREAD

**Issue by pierrekin** [OpenHD/QOpenHD#653]
Would the project be welcoming to an effort (PR / assets / descriptions etc) to support, package for, and publish QOpenHD on the Mac platform and app store?

**Comment by raphaelscholle** [comment]
sure, the only reason why we don't have mac/ios support is that we do not have a dev with mac hardware

**Comment by Consti10** [comment]
We'd be happy about someone both fixing the few remaining things to make qopenhd functional on ios / macos again.
Please note that publishing the app (perhaps monitarized to support openhd development) is not permitted to an indivdual without 
consulting the whole team first.
