### ISSUE TITLE
Cam2 Param busy when there is no second camera, eternal loading indicator

### ISSUE THREAD

**Issue by sound-eng** [OpenHD/QOpenHD#672]
- Displays circular progress indicator that never goes away even though the parameters have been fetched successfully
- Displays CAM2 PARAM BUSY, bu there is just 1 camera defined on air.
- This disables any parameter changes in OHD -> Ground, Air, Air Cam, e t.c.
Sertup is:

QOpenHD from 2.5 evo branch on X86 Ubuntu 22.4
Ground: Pi 4 evo 2.5.3
Air: Pi 2 Zero 2 W evo 2.5.3

**Comment by Consti10** [comment]
unfortunately 2.5.4-alpha (current master) is incompatible with other version(s).
Please try updating openhd core and qopenhd.
Additionally, i recently added a dev flag to disable the autofetch too (OSD->DEV)
(It is only needed if there is no uplink for whatever development reason though)
