### ISSUE TITLE
Want support rockchip mpp decoder

### ISSUE THREAD

**Issue by tbago** [OpenHD/QOpenHD#679]
I use one rockchip 3588 device (OrangePi product) and the device support mpp decoder, I already implement the mpp decoder for QOpenHD and works well for low latency (decoder cost less then 1ms);

I know the project has radax 5B (also use 3588 soc), so maybe it also works well.

So would you like to accept this feature and then I will create the PR.

**Comment by raphaelscholle** [comment]
sure, feel free to do a pull request, we'll look through it and merge if it doesn't interfere with other stuff
Also if you want, please join our development channel, this would allow us to have much easier communication and help you with your task
