### ISSUE TITLE
Use consistent coding style

### ISSUE THREAD

**Issue by steveatinfincia** [OpenHD/QOpenHD#87]
A lot of the code has mixedCase and underscore_case, which is inconsistent but also leads to odd situations where Qt derives the name of a slot automatically, and ends up with `onSlot_nameChanged`.

Qt seems to prefer mixed case, so we should just use it everywhere.

We should also ensure there are 2 spaces between method implementations, and use the /* */ comment style for multi-line comments.

**Comment by pilotnbr1** [comment]
> A lot of the code has mixedCase and underscore_case, which is inconsistent but also leads to odd situations where Qt derives the name of a slot automatically, and ends up with `onSlot_nameChanged`.
> 
> Qt seems to prefer mixed case, so we should just use it everywhere.
> 
> We should also ensure there are 2 spaces between method implementations, and use the /* */ comment style for multi-line comments.

Noted! And guilty :p ... Ill try to some cleanup

**Comment by steveatinfincia** [comment]
Nah it's me, I've been using different case styles every other day :D
