### ISSUE TITLE
Enable screen mirroring on ground station

### ISSUE THREAD

**Issue by steveatinfincia** [OpenHD/QOpenHD#89]
Qt 5.11+ running on KMS supports screen mirroring/cloning directly, which is something we previously could only do by using the special pi firmware (`1to3b_x.elf`), however that was always a bit of a crude hack and people have had trouble getting things to work properly.

To do this in QOpenHD and show the same OSD on the touchscreen as well as HDMI (or multiple HDMI on the pi4), we will have to use the Qt KMS config file, something like this:

    { "device": "/dev/dri/card0",
      "outputs": [ { "name": "HDMI1" },
                   { "name": "DSI", "clones": "HDMI1" } ]
    }

This will only work on the Buster image because we don't use KMS on Stretch. 

It is likely to also require doing video rendering in QOpenHD itself, `hello_video` can't be cloned like this.

Ref: https://doc.qt.io/qt-5.12/embedded-linux.html#advanced-eglfs-kms-features

**Comment by Consti10** [comment]
won't work, at least for the near future (fuck kms)
